# Generated by Django 2.2.1 on 2019-06-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneinfo',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
