# Generated by Django 2.2.1 on 2019-06-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=10)),
                ('pur_date', models.DateTimeField(verbose_name='date purchased')),
            ],
        ),
    ]
