# Generated by Django 2.2.1 on 2019-06-01 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('ticketing', '0002_tickets_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.SceneInfo'),
        ),
    ]
