# Generated by Django 2.2.1 on 2019-06-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_tickets_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_entered',
            field=models.BooleanField(default=False),
        ),
    ]
