# Generated by Django 2.2.1 on 2019-06-01 16:12

from django.db import migrations, models
import ticketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_tickets_is_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='id_code',
            field=models.CharField(default=ticketing.models.Tickets.randomString, max_length=10),
        ),
    ]
