# Generated by Django 2.2.1 on 2019-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20190602_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='tickets',
            name='qrcode_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
